# Generated by Django 3.2.14 on 2023-01-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='img',
            field=models.FileField(default=1, upload_to='image'),
            preserve_default=False,
        ),
    ]
