# Generated by Django 3.2.14 on 2023-01-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20230114_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single',
            name='template',
            field=models.FileField(upload_to='image'),
        ),
    ]
